version: "3.6"

services:
  rstudio:
    image: rocker/rstudio:latest
    container_name: rstudio
    restart: on-failure
    volumes:
      - type: volume
        source: rstudio
        target: /home/rstudio
      - type: bind
        source: C:/Users/xxxxx/xxxxx/Data_R_Docker
        target: /home/rstudio/projects
      - type: volume
        source: r_libs
        target: /usr/local/lib/R
    environment:
      - PASSWORD=rstudio1
    ports:
      - 8787:8787

volumes:
  r_libs:
  rstudio: